name: particles
timestamp: 1611628079
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1468340932
positions:
  sidebar: Sidebar
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  mainbar: Mainbar
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  content:
    system-content-7663: 'Page Content'
  owlcarousel:
    owlcarousel-3850: 'Owl Carousel'
  custom:
    custom-1677: 'OwlCarousel Description'
    custom-2628: 'Content Cubes Description'
    custom-2991: 'Content Tabs Description'
    custom-4781: 'Custom HTML'
  contentcubes:
    contentcubes-4979: 'Content Cubes'
  contenttabs:
    contenttabs-6740: 'Content Tabs'
  position:
    position-position-5748: Sidebar
  menu:
    menu-2193: Menu
  logo:
    logo-6029: 'Logo / Image'
  copyright:
    copyright-2619: Copyright
  social:
    social-2143: Social
  mobile-menu:
    mobile-menu-1854: Mobile-menu
inherit:
  default:
    navigation: navigation
    header: header
    intro: intro
    features: features
    utility: utility
    above: above
    testimonials: testimonials
    expanded: expanded
    mainbar: mainbar
    system-content-7663: system-content-1587
    footer: footer
    offcanvas: offcanvas
    custom-4781: custom-9719
    menu-2193: menu-6409
    logo-6029: logo-4018
    copyright-2619: copyright-1736
    social-2143: social-2639
    mobile-menu-1854: mobile-menu-5697
