name: two_sidebars_right
timestamp: 1611628080
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1468340932
positions: {  }
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  mainbar: Mainbar
  aside: Aside
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  custom:
    custom-6833: Header
    custom-5490: Content
    custom-6361: 'Right Sidebar'
    custom-4736: Lipsum
    custom-9374: 'Flexible Layouts'
    custom-4266: Lipsum
    custom-2767: 'Custom HTML'
  menu:
    menu-2049: Menu
  logo:
    logo-1009: 'Logo / Image'
  copyright:
    copyright-4153: Copyright
  social:
    social-9217: Social
  mobile-menu:
    mobile-menu-9492: Mobile-menu
inherit:
  default:
    navigation: navigation
    footer: footer
    offcanvas: offcanvas
    custom-2767: custom-9719
    menu-2049: menu-6409
    logo-1009: logo-4018
    copyright-4153: copyright-1736
    social-9217: social-2639
    mobile-menu-9492: mobile-menu-5697
