name: right_sidebar
timestamp: 1611628080
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1468340932
positions: {  }
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  mainbar: Mainbar
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  custom:
    custom-6833: Header
    custom-5490: Content
    custom-6361: 'Right Sidebar'
    custom-9374: 'Flexible Layouts'
    custom-3791: 'Custom HTML'
  menu:
    menu-7396: Menu
  logo:
    logo-9260: 'Logo / Image'
  copyright:
    copyright-7255: Copyright
  social:
    social-9095: Social
  mobile-menu:
    mobile-menu-2272: Mobile-menu
inherit:
  default:
    navigation: navigation
    footer: footer
    offcanvas: offcanvas
    custom-3791: custom-9719
    menu-7396: menu-6409
    logo-9260: logo-4018
    copyright-7255: copyright-1736
    social-9095: social-2639
    mobile-menu-2272: mobile-menu-5697
