ordering:
  about:
    res/block-variations: ''
    res/particles: ''
    res/typography: ''
    res/documentation: ''
    res/download: ''
  features:
    fline-page: ''
    ror-page: ''
    og-page: ''
  home: ''
  services:
    left-sidebar: ''
    rows-and-columns: ''
    full-width: ''
    right-sidebar: ''
    two-sidebars: ''
    two-sidebars-left: ''
    two-sidebars-right: ''
  resources: ''
items:
  about:
    object_id: 3
  features:
    object_id: 6
    attributes: {  }
    link_attributes: {  }
    dropdown_dir: right
    dropdown_hide: '0'
    width: auto
  home:
    object_id: 126
    attributes: {  }
    link_attributes: {  }
    dropdown_dir: right
    dropdown_hide: '0'
    width: auto
    image: 'gantry-media://logos/K-Drive-Logo-128x128.png'
    icon_only: '1'
  services:
    object_id: 4
  resources:
    object_id: 5
  layouts/two-sidebars:
    object_id: 70
  pages/offline-page:
    object_id: 118
  layouts/rows-and-columns:
    object_id: 88
  layouts/full-width:
    object_id: 62
  layouts/left-sidebar:
    object_id: 64
  layouts/right-sidebar:
    object_id: 66
  features/block-variations:
    object_id: 43
  layouts/two-sidebars-left:
    object_id: 72
  layouts/two-sidebars-right:
    object_id: 74
  features/particles:
    object_id: 46
  features/typography:
    object_id: 9
  pages/error-page:
    object_id: 7
  features/documentation:
    object_id: 2
  features/download:
    object_id: 1
  pages/blog-page:
    object_id: 128
