name: block_variations
timestamp: 1611628079
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1468340932
positions:
  sidebar: Sidebar
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  mainbar: Mainbar
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  content:
    system-content-1948: 'Page Content'
  custom:
    custom-4778: 'Box 1'
    custom-9665: 'Box 2'
    custom-2425: 'Box Outline'
    custom-4630: 'Box Gradient'
    custom-9906: 'Title 1'
    custom-5672: 'Title 2'
    custom-7940: 'Title Outline'
    custom-9630: 'Title Gradient'
    custom-3865: 'Box 1, Title 1'
    custom-1335: 'Box 2, Title 2'
    custom-2032: 'Box Outline, Title Outline'
    custom-1204: 'Box Gradient, Title Gradient'
    custom-9315: 'Mixed Variations'
    custom-6813: 'Box Gradient, Title 2'
    custom-7550: 'Box Outline, Title 1'
    custom-3068: 'Box Outline, Title Gradient'
    custom-4827: 'Box2, Title 1'
    custom-6016: 'Stylistic Variations'
    custom-2352: 'Box 1, Rounded'
    custom-7473: 'Box Outline, Shadow'
    custom-1717: 'Box 2, Disabled'
    custom-2883: 'Title Outline, Centered Title'
    custom-4523: 'Custom HTML'
  position:
    position-position-3913: Sidebar
  menu:
    menu-2979: Menu
  logo:
    logo-9733: 'Logo / Image'
  copyright:
    copyright-1541: Copyright
  social:
    social-3923: Social
  mobile-menu:
    mobile-menu-1777: Mobile-menu
inherit:
  default:
    navigation: navigation
    header: header
    intro: intro
    features: features
    utility: utility
    above: above
    testimonials: testimonials
    expanded: expanded
    mainbar: mainbar
    system-content-1948: system-content-1587
    footer: footer
    offcanvas: offcanvas
    custom-4523: custom-9719
    menu-2979: menu-6409
    logo-9733: logo-4018
    copyright-1541: copyright-1736
    social-3923: social-2639
    mobile-menu-1777: mobile-menu-5697
